name: check
on:
  push:
    branches:
      - main
      - master
      - develop
      - 'feature/**'
env:
  PROJECT_NAME: my_project
  WORKFLOW: check
jobs:
  run-unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    runs-on: ${{ matrix.os }}
    name: Run tests on Python ${{ matrix.python-version }}, on ${{ matrix.os }}
    timeout-minutes: 45
    concurrency:
      group: ${{ github.workflow }}-run-unit-tests-${{ matrix.python-version }}-${{ matrix.os }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Test
        run: python -m unittest discover -s test -t .
