name: check
on:
  push:
    branches:
      - main
      - master
      - develop
      - 'feature/**'
env:
  PROJECT_NAME: pyxmas
  WORKFLOW: check
jobs:
  run-unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - '3.8'
          - '3.9'
#          - '3.10'
#          - '3.11'
    runs-on: ${{ matrix.os }}
    name: Run tests on Python ${{ matrix.python-version }}, on ${{ matrix.os }}
    timeout-minutes: 45
    concurrency:
      group: ${{ github.workflow }}-run-unit-tests-${{ matrix.python-version }}-${{ matrix.os }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Docker on MacOS
        uses: docker-practice/actions-setup-docker@1.0.11
        if: matrix.os == 'macos-latest'
        timeout-minutes: 12

      - name: Test Docker on Windows
        if: matrix.os == 'windows-latest'
        run: |
          docker compose up --wait
          docker compose logs xmpp-service
          docker compose down

      - name: Docker Info
        run: |
          docker --version
          docker compose version

      - name: Test
        run: python -m unittest discover -s test -t .
